title = "sǝɯɐƃ ǝsnlɔǝɹ"
baseURL = "https://recluse-games.com"
languageCode = "en-US"
theme = "recluse"
tags = ["indie", "games", "game"]
# canonifyURLS = true
# googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies
enableEmoji = true

## Generic theme parameters:
[Params]
  author = "cmallas"
  email = "self@chrisdallas.tech"
  description = "recluse games site"
  tagline = "recluse games"
  logoBig = "/images/recluse-logo.jpg"
  # [str] This is the logo that will be shown in the left corner of the nav bar.
  logoSmall = "favicon.png"
  favicon = "favicon.png"
  googleTagManager = ""
  # [bool] The following will enforce redirection to the baseURL for all sub-directories/-pages.
  #   Example: If you create about.md, Hugo will also create a '/about/index.html'.
  #   This file will only contain a redirect directive if this switch is enabled (recommended, since this is a one-page theme).
  enforceSinglePage = true
  # [bool] Will generate copyright notice in footer for your site.
  copyright = false

## Social media links in footer:
[Params.Social]
  # [str] Link to your Twitter.
  twitter = ""
  # [str] Link to your LinkedIn.
  linkedin = ""
  # [str] Link to your GitHub.
  github = "https://github.com/recluse-games/"
  # [str] Link to your Facebook.
  # facebook = ""
  # [str] Link to your Instagram.
  instagram = ""

## Theme features:
[Params.Feat]
  # [bool] Termynal (https://github.com/ines/termynal) is a small JS library for showing a terminal "animation" from within your gallery item.
  #   The library has been stripped-down to a minimum to only have the necessary functionality.
  useTermynal = true
  # [bool] Lazy loading of images with lazysizes (SEO-friendly).
  lazyloading = true
  googleTagManager = ""
  # [bool] Enable usage of your own 'assets/scss/_custom.css'.
  customCSS = false
  # [bool] Use structured data for your own https://schema.org/Person (SEO-friendly).
  #   The theme attempts to "guess" your information by using the information you give it in the configuration.
  #   For more specific usage, you can override the JSON-LD by supplying your own 'person.json' under 'assets/'
  structuredData = true
  # [str] Tell your GitHub username so that the GitHub API is used to fetch more information for structured data.
  #   This will use information that is publically available about your GitHub user profile at https://api.github.com/users/{USERNAME}.
  # structuredDataFromGithub = "USERNAME"

[[menu.main]]
  name = "Play"
  url  = "/#play"
  weight = 1

[[menu.main]]
  name = "Team"
  url  = "/#team"
  weight = 2

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "recluse-web-target"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://recluse-games.com?region=us-west-2"

# Optionally, you can include or exclude specific files.
# See https://godoc.org/github.com/gobwas/glob#Glob for the glob pattern syntax.
# include = "**.html" # would only include files with ".html" suffix
exclude = "infra/**"

# [[deployment.matchers]] configure behavior for files that match the Pattern.
[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
